services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: ${POSTGRES_DB}
    secrets:
      - db_password
    ports:
      - "5434:5432"
    volumes:
      - cb_pgdata:/var/lib/postgresql
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    security_opt:
    - no-new-privileges=true
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    depends_on:
        db:
          condition: service_healthy
    environment:
        DB_HOST: db
        DB_PORT: 5432
        DB_NAME: ${POSTGRES_DB}
        DB_USER: ${POSTGRES_USER}
        DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - .:/app
    stdin_open: true
    tty: true

secrets:
  db_password:
    file: ./secrets/db_password.txt

volumes:
  cb_pgdata:
